version: '3'

networks:
  networknya:
    driver: bridge

services:
  # php:
  #   container_name: php
  #   build: .docker/php
  #   ports:
  #     - 5173:5173
  #   volumes:
  #     - .././:/var/www:cached
  #   networks:
  #     - networknya

  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   ports:
  #     - 8881:80
  #   volumes:
  #     - .././:/var/www
  #     - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - php
  #   networks:
  #     - networknya

  dbms:
    container_name: dbms
    image: mysql:8.1
    ports:
      - 3306:3306
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/db/logs:/var/log/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=genbigto
      - MYSQL_ROOT_PASSWORD=raisa_isyana
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=root
    networks:
      - networknya

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminc
    restart: unless-stopped
    environment:
      PMA_HOST: dbms  # Use the MySQL service name as the hostname
      PMA_PORT: 3306
    ports:
      - "8882:80"
    depends_on:
      - dbms
    networks:
      - networknya